Controllers/DocumentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web_app_gcd.Data;
using web_app_gcd.Models;
using web_app_gcd.ViewModels;

namespace web_app_gcd.Controllers;

[Authorize]
public class DocumentController : Controller
{
    private ApplicationDbContext _db;

    public DocumentController(ApplicationDbContext db)
    {
        _db = db;
    }

    // GET
    public IActionResult Index()
    {
        var documents = _db.Documents.ToList(); // SELECT * FROM DOCUMENTS
        return View(documents);
    }

    public IActionResult Detail(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        if (documents == null)
        {
            return Content("No find document");
        }
        var chapters = _db.Chapters.Where(c => c.DocumentId == documentId).ToList();
        documents.Chapters = chapters;
        return View(documents);
    }

    public IActionResult Delete(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        if (documents != null)
        {
            _db.Documents.Remove(documents);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Create()
    {
        DocumentCreate formDocument = new DocumentCreate();
        return View(formDocument);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(DocumentCreate document)
    {
        if (ModelState.IsValid)
        {
            Document newDocument = new Document()
            {
                Author = document.Author,
                Image = document.Image,
                Name = document.Name,
                Summary = document.Summary,
                Price = 20,
                UpdateDate = DateTime.Now
            };
            var savedDocument = _db.Documents.Add(newDocument);
            _db.SaveChanges();
            TempData["SUCCESS"] = "Document created successfully";
            return RedirectToAction("Index");
        }
        TempData["ERROR"] = "Document submit is invalid";
        return RedirectToAction("Create");
    }

    [HttpGet]
    public IActionResult Update(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        DocumentUpdate formDocument = new DocumentUpdate()
        {
            Id = documents.Id,
            Author = documents.Author,
            Image = documents.Image,
            Name = documents.Name,
            Price = documents.Price,
            Summary = documents.Summary
        };
        return View(formDocument);
    }

    [HttpPost]
    public IActionResult Update(DocumentUpdate documentUpdate)
    {
        var document = _db.Documents.Find(documentUpdate.Id);
        document.Author = documentUpdate.Author;
        document.Name = documentUpdate.Name;
        document.Image = documentUpdate.Image;
        document.Summary = documentUpdate.Summary;
        document.Price = documentUpdate.Price;
        document.UpdateDate = DateTime.Now;
        _db.SaveChanges();
        string docId = $"{documentUpdate.Id}";
        return RedirectToAction("Detail", new { id = docId });
    }
}

Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Dashboard - Brand</title>
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i">
    <link rel="stylesheet" href="~/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/fonts/fontawesome5-overrides.min.css">
    <link rel="stylesheet" href="~/css/alert.css">
    <link rel="stylesheet" href="~/css/dh-row-titile-text-image-right-1.css">
    <link rel="stylesheet" href="~/css/Form.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/Pretty-Registration-Form.css">
    <link rel="stylesheet" href="~/css/Table-with-search--sort-filters.css">
</head>

<body id="page-top">
<div id="wrapper">
    <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
        <div class="container-fluid d-flex flex-column p-0">
            <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                <div class="sidebar-brand-icon rotate-n-15"></div>
                <div class="sidebar-brand-text mx-3">
                    <span>FPT SYSTEM</span>
                </div>
            </a>
            <hr class="sidebar-divider my-0">
            <ul class="nav navbar-nav text-light" id="accordionSidebar">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Dashboard">
                        <i class="fas fa-tachometer-alt"></i><span>Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="profile.html">
                        <i class="fas fa-user"></i><span>Account</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Document" asp-action="Index"><i class="fas fa-table"></i>Documents</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="login.html">
                        <i class="fa fa-tags"></i><span>Categories</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="register.html">
                        <i class="fas fa-user-circle"></i><span>Register</span>
                    </a>
                </li>
            </ul>
            <div class="text-center d-none d-md-inline">
                <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
            </div>
        </div>
    </nav>
    <div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
            @await RenderSectionAsync("Header", required: true)
            <div class="container-fluid">
                @if (TempData["SUCCESS"] != null)
                {
                    <div class="alert  alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @TempData["SUCCESS"]
                    </div>
                }
                @if (TempData["ERROR"] != null)
                {
                    <div class="alert  alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @TempData["ERROR"]
                    </div>
                }
                @if (TempData["WARNING"] != null)
                {
                    <div class="alert  alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @TempData["WARNING"]
                    </div>
                }
            </div>

            @RenderBody()

        </div>
        <footer class="bg-white sticky-footer">
            <div class="container my-auto">
                <div class="text-center my-auto copyright">
                    <span>Copyright © Brand 2021</span>
                </div>
            </div>
        </footer>
    </div>
    <a class="border rounded d-inline scroll-to-top" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<script src="~/js/chart.min.js"></script>
<script src="~/js/bs-init.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
<script src="~/js/Table-with-search--sort-filters.js"></script>
<script src="~/js/theme.js"></script>
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>@ViewData["Title"] - web_app_gcd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/alert.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dh-navbar-centered-brand.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dh-row-titile-text-image-right-1.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Footer-Dark.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Form.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Pretty-Registration-Form.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Projects-Clean.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Table-with-search--sort-filters.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="~/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/fonts/fontawesome5-overrides.min.css">
</head>
<body class="bg-gradient-primary">
    @* <header> *@
    @*     <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
    @*         <div class="container-fluid"> *@
    @*             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">web_app_gcd</a> *@
    @*             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
    @*                     aria-expanded="false" aria-label="Toggle navigation"> *@
    @*                 <span class="navbar-toggler-icon"></span> *@
    @*             </button> *@
    @*             <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
    @*                 <ul class="navbar-nav flex-grow-1"> *@
    @*                     <li class="nav-item"> *@
    @*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
    @*                     </li> *@
    @*                     <li class="nav-item"> *@
    @*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*                     </li> *@
    @*                 </ul> *@
    @*                 <partial name="_LoginPartial" /> *@
    @*             </div> *@
    @*         </div> *@
    @*     </nav> *@
@* </header> *@
    @RenderBody()
    @* <div class="container"> *@
    @*     <main role="main" class="pb-3"> *@
    @* *@
    @*     </main> *@
    @* </div> *@
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bs-init.js" asp-append-version="true"></script>
    <script src="~/js/chart.min.js" asp-append-version="true"></script>
    <script src="~/js/Table-with-search--sort-filters.js" asp-append-version="true"></script>
    <script src="~/js/theme.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Login - Brand</title>
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i">
    <link rel="stylesheet" href="~/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/fonts/fontawesome5-overrides.min.css">
    <link rel="stylesheet" href="~/css/alert.css">
    <link rel="stylesheet" href="~/css/dh-row-titile-text-image-right-1.css">
    <link rel="stylesheet" href="~/css/Form.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/Pretty-Registration-Form.css">
    <link rel="stylesheet" href="~/css/Table-with-search--sort-filters.css">
</head>

<body class="bg-info">
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/chart.min.js"></script>
    <script src="~/js/bs-init.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Table-with-search--sort-filters.js"></script>
<script src="~/js/theme.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_NavHeader.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject UserManager<ApplicationUser> UserManager
@inject IHttpContextAccessor HttpContextAccessor
@{
 var currentUser=UserManager.GetUserAsync(User).Result;
}
<nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
<div class="container-fluid">
<button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop-1" type="button">
    <i class="fas fa-bars"></i>
</button>
<form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
        <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">
        <div class="input-group-append">
            <button class="btn btn-primary py-0" type="button">
                <i class="fas fa-search"></i>
            </button>
        </div>
    </div>
</form>
<div class="dropdown no-arrow">
    <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#"></a>
    <div class="dropdown-menu dropdown-list dropdown-menu-right animated--grow-in">
        <h6 class="dropdown-header">alerts center</h6>
        <a class="d-flex align-items-center dropdown-item" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="~/img/avatars/avatar4.jpeg">
                <div class="bg-success status-indicator"></div>
            </div>
            <div class="font-weight-bold">
                <div class="text-truncate">
                    <span>Hi there! I am wondering if you can help me with a problem I've been having.</span>
                </div>
                <p class="small text-gray-500 mb-0">Emily Fowler - 58m</p>
            </div>
        </a>
        <a class="d-flex align-items-center dropdown-item" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="~/img/avatars/avatar2.jpeg">
                <div class="status-indicator"></div>
            </div>
            <div class="font-weight-bold">
                <div class="text-truncate">
                    <span>I have the photos that you ordered last month!</span>
                </div>
                <p class="small text-gray-500 mb-0">Jae Chun - 1d</p>
            </div>
        </a>
        <a class="d-flex align-items-center dropdown-item" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="~/img/avatars/avatar3.jpeg">
                <div class="bg-warning status-indicator"></div>
            </div>
            <div class="font-weight-bold">
                <div class="text-truncate">
                    <span>Last month's report looks great, I am very happy with the progress so far, keep up the good work!</span>
                </div>
                <p class="small text-gray-500 mb-0">Morgan Alvarez - 2d</p>
            </div>
        </a>
        <a class="d-flex align-items-center dropdown-item" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="~/img/avatars/avatar5.jpeg">
                <div class="bg-success status-indicator"></div>
            </div>
            <div class="font-weight-bold">
                <div class="text-truncate">
                    <span>Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</span>
                </div>
                <p class="small text-gray-500 mb-0">Chicken the Dog · 2w</p>
            </div>
        </a><a class="text-center dropdown-item small text-gray-500" href="#">Show All Alerts</a>
    </div>
</div>
<ul class="nav navbar-nav flex-nowrap ml-auto">
    <li class="nav-item dropdown d-sm-none no-arrow">
        <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">
            <i class="fas fa-search"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" aria-labelledby="searchDropdown">
            <form class="form-inline mr-auto navbar-search w-100">
                <div class="input-group">
                    <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">
                    <div class="input-group-append">
                        <button class="btn btn-primary py-0" type="button">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
        <div class="nav-item dropdown no-arrow">
            <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">
                <span class="badge badge-danger badge-counter">3+</span><i class="fas fa-bell fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-list dropdown-menu-right animated--grow-in">
                <h6 class="dropdown-header">alerts center</h6>
                <a class="d-flex align-items-center dropdown-item" href="#">
                    <div class="mr-3">
                        <div class="bg-primary icon-circle">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <span class="small text-gray-500">December 12, 2019</span>
                        <p>A new monthly report is ready to download!</p>
                    </div>
                </a>
                <a class="d-flex align-items-center dropdown-item" href="#">
                    <div class="mr-3">
                        <div class="bg-success icon-circle">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <span class="small text-gray-500">December 7, 2019</span>
                        <p>$290.29 has been deposited into your account!</p>
                    </div>
                </a>
                <a class="d-flex align-items-center dropdown-item" href="#">
                    <div class="mr-3">
                        <div class="bg-warning icon-circle">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <span class="small text-gray-500">December 2, 2019</span>
                        <p>Spending Alert: We've noticed unusually high spending for your account.</p>
                    </div>
                </a><a class="text-center dropdown-item small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
        <div class="nav-item dropdown no-arrow">
            <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">
                <i class="fas fa-envelope fa-fw"></i><span class="badge badge-danger badge-counter">7</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-list dropdown-menu-right animated--grow-in">
                <h6 class="dropdown-header">alerts center</h6>
                <a class="d-flex align-items-center dropdown-item" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="~/img/avatars/avatar4.jpeg">
                        <div class="bg-success status-indicator"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">
                            <span>Hi there! I am wondering if you can help me with a problem I've been having.</span>
                        </div>
                        <p class="small text-gray-500 mb-0">Emily Fowler - 58m</p>
                    </div>
                </a>
                <a class="d-flex align-items-center dropdown-item" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="~/img/avatars/avatar2.jpeg">
                        <div class="status-indicator"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">
                            <span>I have the photos that you ordered last month!</span>
                        </div>
                        <p class="small text-gray-500 mb-0">Jae Chun - 1d</p>
                    </div>
                </a>
                <a class="d-flex align-items-center dropdown-item" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="~/img/avatars/avatar3.jpeg">
                        <div class="bg-warning status-indicator"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">
                            <span>Last month's report looks great, I am very happy with the progress so far, keep up the good work!</span>
                        </div>
                        <p class="small text-gray-500 mb-0">Morgan Alvarez - 2d</p>
                    </div>
                </a>
                <a class="d-flex align-items-center dropdown-item" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="~/img/avatars/avatar5.jpeg">
                        <div class="bg-success status-indicator"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">
                            <span>Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</span>
                        </div>
                        <p class="small text-gray-500 mb-0">Chicken the Dog · 2w</p>
                    </div>
                </a><a class="text-center dropdown-item small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </div>
        <div class="shadow dropdown-list dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown"></div>
    </li>
    <div class="d-none d-sm-block topbar-divider"></div>
    <li class="nav-item dropdown no-arrow">
        <div class="nav-item dropdown no-arrow">
            <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">
                <span class="d-none d-lg-inline mr-2 text-gray-600 small">@currentUser.UserName</span><img class="border rounded-circle img-profile" src="@currentUser.Avatar" alt="">
            </a>
            <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                <a class="dropdown-item" href="#"><i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Profile</a>
                <a class="dropdown-item" href="#"><i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Settings</a>
                <a class="dropdown-item" href="#"><i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Activity log</a>
                <div class="dropdown-divider"></div>
                <form class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;
                    <button type="submit">
                        Logout
                    </button>
                </form>
            </div>
        </div>
    </li>
</ul>
</div>
</nav>

Views/Shared/_Notification.cshtml
@* <div class="alert alert-success" role="alert" id="save-sucess" style="background-color: #B4F7D2!important; border: 1px solid #0C6D38;"> *@
@*     <button type="button" class="close" data-dismiss="alert" aria-label="Close"> *@
@*         <span aria-hidden="true">×</span> *@
@*     </button><i class="icon ion-checkmark-round mr-1"></i><span style="color: #0C6D38 !important;">Create Course successfully<br></span> *@
@* </div> *@
@* <div class="alert alert-success" role="alert" id="save-sucess-1" style="border: 1px solid #0C6D38;background: var(--danger);"> *@
@*     <button type="button" class="close" data-dismiss="alert" aria-label="Close"> *@
@*         <span aria-hidden="true">×</span> *@
@*     </button><i class="icon ion-close mr-1"></i><span style="color: #0C6D38 !important;">Can't not create course<br></span> *@
@* </div> *@
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}