Models/Document.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace web_app_gcd.Models;

public class Document
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Author { get; set; }
    public string Image { get; set; }
    public string Summary { get; set; }
    public DateTime UpdateDate { get; set; } // Ko hien thi form
    public int Price { get; set; } // // Ko hien thi form
    
    public List<Chapter>? Chapters { get; set; }
    public DateTime CreatedAt { get; set; }

    public Document()
    {
        this.CreatedAt = DateTime.Now;
    }

}

Controllers/ChapterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web_app_gcd.Data;
using web_app_gcd.Models;
using web_app_gcd.ViewModels;

namespace web_app_gcd.Controllers;

[Authorize]
public class ChapterController : Controller
{
    private readonly ApplicationDbContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public ChapterController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
    {
        _userManager = userManager;
        _db = db;
    }
    // GET
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Create(int id)
    {
        ChapterCreate chapterCreate = new ChapterCreate()
        {
            DocumentId = id
        };
        return View(chapterCreate);
    }
    
    [HttpPost]
    public IActionResult Create(ChapterCreate chapterCreate)
    {
        Document? documentInDb = _db.Documents.Find(chapterCreate.DocumentId);
        if (documentInDb == null)
        {
            return Content("Error");
        }
        Chapter chapter = new Chapter()
        {
            DocumentId = chapterCreate.DocumentId,
            Content =  chapterCreate.Content,
            Document = documentInDb
        };
        _db.Chapters.Add(chapter);
        _db.SaveChanges();
        return RedirectToAction("Detail", "Document", new { id = chapterCreate.DocumentId });
    }

    public IActionResult Detail(int id)
    {
        var chapter = _db.Chapters
            .Include(c => c.Document)
            .FirstOrDefault(d => d.Id == id);
        if (chapter != null)
        {
            var chapterRelated = _db.Chapters.Where(c => c.DocumentId == chapter.DocumentId).ToList();
            chapterRelated.Remove(chapter);
            ChapterDetail chapterDetail = new ChapterDetail()
            {
                Chapter = chapter,
                Chapters = chapterRelated
            };
            if (chapter.IsFree)
            {
                return View(chapterDetail);
            }

            var userId = _userManager.GetUserId(HttpContext.User);
            var allowAccess = _db.Accesses.FirstOrDefault(a => a.DocumentId == chapter.DocumentId && a.UserId == userId);
            if (allowAccess != null && allowAccess.ExpDate > DateTime.Now)
            {
                return View(chapterDetail);
            }
            return Content("You deo dc coi");

        }
        return Content("Not find chapter");
    }
}

Controllers/DocumentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web_app_gcd.Data;
using web_app_gcd.Models;
using web_app_gcd.ViewModels;

namespace web_app_gcd.Controllers;

[Authorize]
public class DocumentController : Controller
{
    private ApplicationDbContext _db;

    public DocumentController(ApplicationDbContext db)
    {
        _db = db;
    }

    // GET
    public IActionResult Index()
    {
        var documents = _db.Documents.ToList(); // SELECT * FROM DOCUMENTS
        return View(documents);
    }

    public IActionResult Detail(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        if (documents == null)
        {
            return Content("No find document");
        }
        var chapters = _db.Chapters.Where(c => c.DocumentId == documentId).ToList();
        documents.Chapters = chapters;
        return View(documents);
    }

    public IActionResult Delete(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        if (documents != null)
        {
            _db.Documents.Remove(documents);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Create()
    {
        DocumentCreate formDocument = new DocumentCreate();
        return View(formDocument);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(DocumentCreate document)
    {
        if (ModelState.IsValid)
        {
            Document newDocument = new Document()
            {
                Author = document.Author,
                Image = document.Image,
                Name = document.Name,
                Summary = document.Summary,
                Price = 20,
                UpdateDate = DateTime.Now
            };
            var savedDocument = _db.Documents.Add(newDocument);
            _db.SaveChanges();
            TempData["SUCCESS"] = "Document created successfully";
            return RedirectToAction("Index");
        }
        TempData["ERROR"] = "Document submit is invalid";
        return RedirectToAction("Create");
    }

    [HttpGet]
    public IActionResult Update(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        DocumentUpdate formDocument = new DocumentUpdate()
        {
            Id = documents.Id,
            Author = documents.Author,
            Image = documents.Image,
            Name = documents.Name,
            Price = documents.Price,
            Summary = documents.Summary
        };
        return View(formDocument);
    }

    [HttpPost]
    public IActionResult Update(DocumentUpdate documentUpdate)
    {
        var document = _db.Documents.Find(documentUpdate.Id);
        document.Author = documentUpdate.Author;
        document.Name = documentUpdate.Name;
        document.Image = documentUpdate.Image;
        document.Summary = documentUpdate.Summary;
        document.Price = documentUpdate.Price;
        document.UpdateDate = DateTime.Now;
        _db.SaveChanges();
        string docId = $"{documentUpdate.Id}";
        return RedirectToAction("Detail", new { id = docId });
    }
}

Views/Document/Create.cshtml
@model web_app_gcd.ViewModels.DocumentCreate

@{
    ViewBag.Title = "Document Create";
    Layout = "_DashboardLayout";
}

@section Header {
    <partial name="_NavHeader"/>
}
<div class="container-fluid">
    <h3 class="text-dark mb-1">Document Create</h3>
</div>
<div class="row register-form">
    <div class="col-md-8 offset-md-2">
        <form class="custom-form" asp-action="Create" method="post">
            <h1>Document Form</h1>
            <div class="form-row form-group">
                <div class="col-sm-4 label-column">
                    <label class="col-form-label" asp-for="Name">Name </label>
                </div>
                <div class="col-sm-6 input-column">
                    <input class="form-control" type="text" asp-for="Name">
                </div>
            </div>
            <div class="form-row form-group">
                <div class="col-sm-4 label-column">
                    <label class="col-form-label" asp-for="Author">Author</label>
                </div>
                <div class="col-sm-6 input-column">
                    <input class="form-control" type="text" asp-for="Author">
                </div>
            </div>
            <div class="form-row form-group">
                <div class="col-sm-4 label-column">
                    <label class="col-form-label" asp-for="Image">Image</label>
                </div>
                <div class="col-sm-4 input-column">
                    <input type="text" asp-for="Image">
                </div>
            </div>
            <div class="form-row form-group">
                <div class="col-sm-4 label-column">
                    <label class="col-form-label" asp-for="Summary">Summary</label>
                </div>
                <div class="col-sm-4 input-column">
                    @(Html.TextAreaFor(m => m.Summary))
                </div>
            </div>
            <button class="btn btn-light submit-button" type="submit">Save</button>
        </form>
    </div>
</div>

Views/Document/Detail.cshtml
@model Document

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<button type="button">
    <a asp-action="Index">Back</a>
</button>
@{
    if (User.IsInRole(RoleApp.Staff))
    {
        <button type="button">
            <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
        </button>
        <button type="button">
            <a asp-action="Update" asp-route-id="@Model.Id">Update</a>
        </button>
        <button type="button">
            <a asp-controller="Chapter" asp-action="Create" asp-route-id="@Model.Id">Create chapter</a>
        </button>
    }
    else
    {
        <button type="button">
            <a asp-controller="Chapter" asp-action="Create" asp-route-id="@Model.Id">Request documentr</a>
        </button>
    }
}

@{
    <div class="card">
        <img src="@Model.Image" alt="Avatar" style="width:300px;height: 300px">
        <div class="container">
            <h4>
                <b>
                    <a>@Model.Name</a>
                </b>
            </h4>
            <h5>
                <b>
                    <a>@Model.Id</a>
                </b>
            </h5>
            <p>@Model.Author</p>
            <p>@Model.Price</p>
            <p>@Model.Summary</p>
            <p>@Model.CreatedAt</p>
            <ul>
                <h5>Chapter</h5>
                @{
                    if (Model.Chapters == null)
                    {
                        <li>No chapter for document</li>
                    }
                    else
                    {
                        foreach (var chapter in Model.Chapters)
                        {
                            <li>
                                <a asp-controller="Chapter" asp-action="Detail" asp-route-id="@chapter.Id">@chapter.Content</a>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
    </div>
}

Views/Document/Index.cshtml
@model List<Document>

@{
    ViewBag.Title = "Document index";
    Layout = "_DashboardLayout";
}
@section Header {
    <partial name="_NavHeader"/>
}
<div class="container-fluid">
    <h3 class="text-dark mb-4">Documents</h3>
    <div class="card-header py-3 ">
        <button type="button" class="btn btn-info">
            <a class="text-primary m-0 font-weight-bold" asp-controller="Document" asp-action="Create">Create</a>
        </button>
    </div>
    <div class="card shadow">
        <div class="card-header py-3">
            <p class="text-primary m-0 font-weight-bold">List document</p>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 text-nowrap">
                    <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable">
                        <label>
                            Show&nbsp;
                            <select class="form-control form-control-sm custom-select custom-select-sm">
                                <option value="1" selected="">1</option>
                                <option value="5">5</option>
                                <option value="10">10</option>
                            </select>&nbsp;
                        </label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="text-md-right dataTables_filter" id="dataTable_filter">
                        <label>
                            <input type="search" class="form-control form-control-sm" aria-controls="dataTable" placeholder="Search">
                        </label>
                    </div>
                </div>
            </div>
            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                <table class="table my-0" id="dataTable">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Id</th>
                        <th>Author</th>
                        <th>Price</th>
                        <th>UpdateDate</th>
                        <th>CreatedAt</th>
                    </tr>
                    </thead>
                    <tbody>
                    @{
                        foreach (var document in Model)
                        {
                            <tr>
                                <td><img class="rounded-circle mr-2" width="30" height="30" src="@document.Image">@document.Name</td>
                                <td>@document.Id</td>
                                <td>@document.Author</td>
                                <td>@document.Price</td>
                                <td>@document.CreatedAt</td>
                                <td>@document.UpdateDate</td>
                            </tr>
                        }
                        
                    }

                    </tbody>
                    <tfoot>
                    <tr>
                        <td>
                            <strong>Name</strong>
                        </td>
                        <td>
                            <strong>Position</strong>
                        </td>
                        <td>
                            <strong>Office</strong>
                        </td>
                        <td>
                            <strong>Age</strong>
                        </td>
                        <td>
                            <strong>Start date</strong>
                        </td>
                        <td>
                            <strong>Salary</strong>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
            <div class="row">
                <div class="col-md-6 align-self-center">
                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Showing 1 to 10 of 27</p>
                </div>
                <div class="col-md-6">
                    <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" aria-label="Previous">
                                    <span aria-hidden="true">«</span>
                                </a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Next">
                                    <span aria-hidden="true">»</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Document/Update.cshtml
@model web_app_gcd.ViewModels.DocumentUpdate

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Form create Document</h2>
<form asp-action="Update" method="post">
    <label asp-for="Name">Name</label>
    <input type="text" asp-for="Name" value="@Model.Name">
    <label asp-for="Author">Author</label>
    <input type="text" asp-for="Author" value="@Model.Author">
    <label asp-for="Image">Image</label>
    <input type="text" asp-for="Image" value="@Model.Image">
    <label asp-for="Summary">Summary</label>
    <input type="text" asp-for="Summary" value="@Model.Summary">
    <label asp-for="Price">Summary</label>
    <input type="text" asp-for="Price" value="@Model.Price">
    <button type="submit">Save</button>
</form>